# Site settings
title: Paweł Kaleta
email: pawel.krzysztof.kaleta@gmail.com
description: > # keep this and put description below
  An ambitious, eager-to-learn and self-taught, aspiring programmer with analytical prowess and some basic overall game-dev knowledge.
url: "https://pawel-kaleta.github.io" # the base hostname & protocol for your site
#linkedin_url: "https://www.linkedin.com/in/gamingportfolio"
github_username: pawel-kaleta
#twitter_username: gamingportfolio
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
